spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/airline_reservation
    username: postgres
    password: 1
  jpa:
    hibernate:
      ddl-auto: none

logging:
  level:
    org:
      hibernate: info
